package com.qihoo.tbtool.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.qihoo.tbtool.bean.SelectProperty;

import com.qihoo.tbtool.dao.SelectPropertyDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig selectPropertyDaoConfig;

    private final SelectPropertyDao selectPropertyDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        selectPropertyDaoConfig = daoConfigMap.get(SelectPropertyDao.class).clone();
        selectPropertyDaoConfig.initIdentityScope(type);

        selectPropertyDao = new SelectPropertyDao(selectPropertyDaoConfig, this);

        registerDao(SelectProperty.class, selectPropertyDao);
    }
    
    public void clear() {
        selectPropertyDaoConfig.clearIdentityScope();
    }

    public SelectPropertyDao getSelectPropertyDao() {
        return selectPropertyDao;
    }

}
