package com.qihoo.tbtool.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.qihoo.tbtool.dao.converter.TBPropertyConverter;
import java.util.HashMap;

import com.qihoo.tbtool.bean.SelectProperty;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "SELECT_PROPERTY".
*/
public class SelectPropertyDao extends AbstractDao<SelectProperty, Long> {

    public static final String TABLENAME = "SELECT_PROPERTY";

    /**
     * Properties of entity SelectProperty.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "id");
        public final static Property ItemId = new Property(1, String.class, "itemId", false, "item_id");
        public final static Property TbProperty = new Property(2, String.class, "tbProperty", false, "TB_PROPERTY");
    }

    private final TBPropertyConverter tbPropertyConverter = new TBPropertyConverter();

    public SelectPropertyDao(DaoConfig config) {
        super(config);
    }
    
    public SelectPropertyDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"SELECT_PROPERTY\" (" + //
                "\"id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"item_id\" TEXT," + // 1: itemId
                "\"TB_PROPERTY\" TEXT);"); // 2: tbProperty
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"SELECT_PROPERTY\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, SelectProperty entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String itemId = entity.getItemId();
        if (itemId != null) {
            stmt.bindString(2, itemId);
        }
 
        HashMap tbProperty = entity.getTbProperty();
        if (tbProperty != null) {
            stmt.bindString(3, tbPropertyConverter.convertToDatabaseValue(tbProperty));
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, SelectProperty entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String itemId = entity.getItemId();
        if (itemId != null) {
            stmt.bindString(2, itemId);
        }
 
        HashMap tbProperty = entity.getTbProperty();
        if (tbProperty != null) {
            stmt.bindString(3, tbPropertyConverter.convertToDatabaseValue(tbProperty));
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public SelectProperty readEntity(Cursor cursor, int offset) {
        SelectProperty entity = new SelectProperty( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // itemId
            cursor.isNull(offset + 2) ? null : tbPropertyConverter.convertToEntityProperty(cursor.getString(offset + 2)) // tbProperty
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, SelectProperty entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setItemId(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setTbProperty(cursor.isNull(offset + 2) ? null : tbPropertyConverter.convertToEntityProperty(cursor.getString(offset + 2)));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(SelectProperty entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(SelectProperty entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(SelectProperty entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
